export const NEWS_LETTERS_DOMAINS = [
  // Developer & Programming Newsletters
  { name: "The New Stack", domain: "thenewstack.io" },
  { name: "Medium", domain: "medium.com" },
  { name: "Pocket", domain: "today.getpocket.com" },
  { name: "Console Dev", domain: "console.dev" },
  { name: "Daily.dev", domain: "daily.dev" },
  { name: "HackerNoon", domain: "hackernoon.com" },
  { name: "Smashing Magazine", domain: "smashingmagazine.com" },
  { name: "CSS-Tricks", domain: "css-tricks.com" },
  { name: "Hashnode", domain: "hashnode.com" },
  { name: "Web.dev", domain: "web.dev" },
  { name: "Frontend Focus", domain: "frontendfocus.co" },
  { name: "Node Weekly", domain: "nodeweekly.com" },
  { name: "React Status", domain: "react.statuscode.com" },
  { name: "JavaScript Weekly", domain: "javascriptweekly.com" },
  { name: "Ruby Weekly", domain: "rubyweekly.com" },
  { name: "Go Weekly", domain: "goweekly.com" },
  { name: "Python Weekly", domain: "pythonweekly.com" },
  { name: "Kotlin Weekly", domain: "kotlinweekly.net" },
  { name: ".NET Weekly", domain: "dotnetweekly.com" },
  { name: "This Week in Rust", domain: "this-week-in-rust.org" },
  { name: "Android Weekly", domain: "androidweekly.net" },
  { name: "iOS Dev Weekly", domain: "iosdevweekly.com" },
  { name: "DevOps’ish", domain: "devopsish.com" },
  { name: "Dev.to", domain: "dev.to" },
  { name: "Changelog", domain: "changelog.com" },
  { name: "ByteByteGo", domain: "bytebytego.com" },
  { name: "Pointer.io", domain: "pointer.io" },
  { name: "Programming Digest", domain: "programmingdigest.net" },
  { name: "TLDR Tech", domain: "tldr.tech" },
  { name: "Cooperpress", domain: "cooperpress.com" },
  { name: "Bytes", domain: "bytes.dev" },
  { name: "Frontend Horse", domain: "frontend.horse" },
  { name: "UI Dev Newsletter", domain: "ui.dev" },

  // AI, Data Science & Machine Learning
  { name: "Inside Big Data", domain: "insidebigdata.com" },
  { name: "Towards Data Science", domain: "towardsdatascience.com" },
  { name: "Import AI", domain: "importai.net" },
  { name: "Last Week in AI", domain: "lastweekin.ai" },
  { name: "The Gradient", domain: "thegradient.pub" },

  // Cloud & DevOps
  { name: "AWS Weekly", domain: "awsweekly.com" },
  { name: "GCP Weekly", domain: "gcpweekly.com" },
  { name: "Azure Weekly", domain: "azureweekly.com" },
  { name: "Kubelist", domain: "kubelist.com" },
  { name: "Kube Weekly", domain: "kubeweekly.io" },
  { name: "DevOps Weekly", domain: "devopsweekly.com" },
  { name: "Cloud Weekly", domain: "cloudweekly.net" },
  { name: "Serverless Weekly", domain: "serverlessweekly.com" },
  { name: "Terraform Weekly", domain: "terraformweekly.com" },
  { name: "DevOps Links", domain: "devopslinks.com" },
  { name: "Kubernetes News", domain: "kubernetes.news" },

  // Security & Cybersecurity
  { name: "Krebs on Security", domain: "krebsonsecurity.com" },
  { name: "Dark Reading", domain: "darkreading.com" },
  { name: "Security Week", domain: "securityweek.com" },
  { name: "ThreatPost", domain: "threatpost.com" },
  { name: "Cyber Weekly", domain: "cyberweekly.net" },
  { name: "Schneier on Security", domain: "schneier.com" },
  { name: "The Hacker News", domain: "thehackernews.com" },
  { name: "Security Newsletter", domain: "securitynewsletter.co" },
  { name: "SANS NewsBites", domain: "sans.org" },
  { name: "Cybersecurity Dive", domain: "cybersecuritydive.com" },
  { name: "Threat Intelligence Weekly", domain: "threatintelligenceweekly.com" },
  { name: "Security Weekly", domain: "securityweekly.com" },
  { name: "Malwarebytes Labs", domain: "blog.malwarebytes.com" },
  { name: "BleepingComputer", domain: "bleepingcomputer.com" },
  { name: "CyberScoop", domain: "cyberscoop.com" },

  // Blockchain & Crypto
  { name: "Decrypt", domain: "decrypt.co" },
  { name: "CoinTelegraph", domain: "cointelegraph.com" },
  { name: "Bankless", domain: "banklesshq.com" },
  { name: "The Defiant", domain: "thedefiant.io" },

  // Tech Industry & General News
  { name: "TechCrunch", domain: "techcrunch.com" },
  { name: "Wired", domain: "wired.com" },
  { name: "The Verge", domain: "theverge.com" },
  { name: "Ars Technica", domain: "arstechnica.com" },
  { name: "The Next Web (TNW)", domain: "thenextweb.com" },
  { name: "Fast Company", domain: "fastcompany.com" },
  { name: "VentureBeat", domain: "venturebeat.com" },
  { name: "Engadget", domain: "engadget.com" },
  { name: "Pragmatic Engineer", domain: "pragmaticengineer.com" },
  { name: "Level Up", domain: "levelup.patkua.com" },
  { name: "Software Lead Weekly", domain: "softwareleadweekly.com" },
  { name: "Tech Lead Digest", domain: "techleaddigest.net" },

  // Open Source & Miscellaneous
  { name: "OpenSource.com", domain: "opensource.com" },
  { name: "Red Hat", domain: "redhat.com" },
  { name: "Linux Foundation", domain: "linuxfoundation.org" },
  { name: "DistroWatch", domain: "distrowatch.com" },
  { name: "GitHub Universe", domain: "githubuniverse.com" },
  { name: "Open Source Weekly", domain: "opensourceweekly.co" },
  { name: "Open Source Initiative", domain: "opensource.org" },
  { name: "Free Software Foundation", domain: "fsf.org" },
  { name: "HackerRank Blog", domain: "blog.hackerrank.com" },
  { name: "CodeProject", domain: "codeproject.com" },
  { name: "CodePen", domain: "codepen.io" },
  { name: "GitHub Changelog", domain: "githubchangelog.com" },

  // System Design & Architecture
  { name: "High Scalability", domain: "highscalability.com" },
  { name: "Architecture Notes", domain: "architecturenotes.co" },
  { name: "System Design Newsletter", domain: "systemdesign.one" },
  { name: "System Design Primer", domain: "systemdesignprimer.com" },
  { name: "The System Design Podcast", domain: "systemdesignpodcast.com" },
  { name: "Software Architecture Weekly", domain: "softwarearchitectureweekly.com" },
  { name: "Tech Lead Weekly", domain: "techleadweekly.com" },

  // AI & ML Specific
  { name: "The Batch", domain: "deeplearning.ai" },
  { name: "The ML Engineer", domain: "themlengineers.com" },
  { name: "The Sequence", domain: "thesequence.ai" },
  { name: "The Algorithm", domain: "thealgorithm.ai" },
  { name: "AI Weekly", domain: "aiweekly.co" },
  { name: "Data Elixir", domain: "dataelixir.com" },
  { name: "Data Science Weekly", domain: "datascienceweekly.com" },
  { name: "The AI Alignment Forum", domain: "alignmentforum.org" },
  { name: "The AI Report", domain: "thereport.ai" },
  { name: "AI in Business", domain: "aiinbusiness.com" },
];

export const TECH_KEYWORDS = [
  // Programming Languages
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "TypeScript",
  "PHP",
  "Perl",
  "Scala",
  "Dart",
  "Elixir",
  "Haskell",
  "Lua",
  "R",
  "MATLAB",
  "Shell",
  "Bash",

  // Software Development
  "development",
  "software",
  "app",
  "mobile",
  "web",
  "framework",
  "library",
  "backend",
  "frontend",
  "fullstack",
  "API",
  "SDK",
  "microservices",
  "serverless",
  "REST",
  "GraphQL",
  "gRPC",
  "RPC",
  "CI/CD",
  "testing",
  "unit testing",
  "integration testing",
  "TDD",
  "BDD",
  "functional programming",
  "object-oriented programming",
  "design patterns",
  "scalability",
  "performance optimization",

  // DevOps & Cloud
  "DevOps",
  "Cloud",
  "AWS",
  "Google Cloud",
  "Azure",
  "DigitalOcean",
  "Heroku",
  "Netlify",
  "Vercel",
  "Firebase",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitHub Actions",
  "CI/CD",
  "Kubernetes",
  "Docker",
  "Containers",
  "Serverless",
  "Helm",
  "OpenShift",
  "Cloudflare",
  "Infrastructure as Code",

  // AI & Machine Learning
  "AI",
  "artificial intelligence",
  "machine learning",
  "deep learning",
  "neural networks",
  "NLP",
  "computer vision",
  "GPT",
  "LLM",
  "transformers",
  "data science",
  "big data",
  "analytics",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-Learn",
  "Pandas",
  "NumPy",
  "data engineering",
  "data pipelines",
  "ETL",
  "SQL",
  "NoSQL",
  "Hadoop",
  "Spark",
  "Kafka",
  "Airflow",

  // Security & Cybersecurity
  "cybersecurity",
  "penetration testing",
  "ethical hacking",
  "encryption",
  "hashing",
  "SSL/TLS",
  "authentication",
  "OAuth",
  "JWT",
  "firewalls",
  "SOC",
  "SIEM",
  "zero trust",
  "IAM",
  "data privacy",
  "compliance",
  "ISO 27001",
  "GDPR",
  "SOC2",
  "OWASP",
  "malware",
  "phishing",
  "ransomware",

  // Blockchain & Web3
  "blockchain",
  "Web3",
  "decentralization",
  "Ethereum",
  "Solidity",
  "smart contracts",
  "NFTs",
  "DeFi",
  "Bitcoin",
  "crypto",
  "DApps",
  "Metaverse",
  "ledger",
  "IPFS",
  "gas fees",
  "staking",
  "mining",
  "proof of work",
  "proof of stake",

  // Hardware & Devices
  "hardware",
  "gadgets",
  "devices",
  "laptops",
  "processors",
  "GPUs",
  "chips",
  "components",
  "ARM",
  "x86",
  "Raspberry Pi",
  "Arduino",
  "IoT",
  "5G",
  "edge computing",
  "wearables",
  "robotics",
  "autonomous vehicles",
  "drones",
  "VR",
  "AR",
  "XR",
  "smart home",

  // Tools & Platforms
  "Node.js",
  "React",
  "Vue",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Remix",
  "Electron",
  "Flutter",
  "React Native",
  "SwiftUI",
  "Jetpack Compose",
  "Bootstrap",
  "Tailwind CSS",
  "Material UI",
  "GraphQL",
  "Prisma",
  "Django",
  "Spring Boot",
  "Express.js",
  "NestJS",
  "FastAPI",
  "Flask",
  "Ruby on Rails",
  "Laravel",
  "ASP.NET",
  "Unity",
  "Unreal Engine",
  "WebAssembly",
  "Rust",
  "LLVM",
  "WebRTC",
  "Three.js",

  // Tech Trends & Community
  "technology",
  "innovation",
  "startups",
  "Silicon Valley",
  "tech industry",
  "open source",
  "developer advocacy",
  "tech conferences",
  "hackathons",
  "Google I/O",
  "WWDC",
  "re:Invent",
  "KubeCon",
  "DEFCON",
  "CES",
  "FOSDEM",
  "Black Hat",
  "PyCon",
  "JSConf",

  // Learning & Resources
  "trends",
  "tutorial",
  "guide",
  "course",
  "certification",
  "bootcamp",
  "MOOC",
  "Codecademy",
  "Udemy",
  "Coursera",
  "Pluralsight",
  "edX",
  "LeetCode",
  "HackerRank",
  "Codeforces",
  "competitive programming",
  "tech blogs",
  "GitHub",
  "Stack Overflow",
  "Reddit",
  "Medium",
  "newsletter",
  "update",
  "weekly digest",
];
