export const NEWS_LETTERS_DOMAINS = [
  // Developer & Programming Newsletters
  { name: "The New Stack", domain: "thenewstack.io" },
  { name: "Medium", domain: "medium.com" },
  { name: "Pocket", domain: "today.getpocket.com" },
  { name: "Console Dev", domain: "console.dev" },
  { name: "Daily.dev", domain: "daily.dev" },
  { name: "HackerNoon", domain: "hackernoon.com" },
  { name: "Smashing Magazine", domain: "smashingmagazine.com" },
  { name: "CSS-Tricks", domain: "css-tricks.com" },
  { name: "Hashnode", domain: "hashnode.com" },
  { name: "Web.dev", domain: "web.dev" },
  { name: "Frontend Focus", domain: "frontendfocus.co" },
  { name: "Node Weekly", domain: "nodeweekly.com" },
  { name: "React Status", domain: "react.statuscode.com" },
  { name: "JavaScript Weekly", domain: "javascriptweekly.com" },
  { name: "Ruby Weekly", domain: "rubyweekly.com" },
  { name: "Go Weekly", domain: "goweekly.com" },
  { name: "Python Weekly", domain: "pythonweekly.com" },
  { name: "Kotlin Weekly", domain: "kotlinweekly.net" },
  { name: ".NET Weekly", domain: "dotnetweekly.com" },
  { name: "This Week in Rust", domain: "this-week-in-rust.org" },
  { name: "Android Weekly", domain: "androidweekly.net" },
  { name: "iOS Dev Weekly", domain: "iosdevweekly.com" },
  { name: "DevOps’ish", domain: "devopsish.com" },

  // AI, Data Science & Machine Learning
  { name: "Inside Big Data", domain: "insidebigdata.com" },
  { name: "Towards Data Science", domain: "towardsdatascience.com" },
  { name: "Import AI", domain: "importai.net" },
  { name: "Last Week in AI", domain: "lastweekin.ai" },
  { name: "The Gradient", domain: "thegradient.pub" },

  // Cloud & DevOps
  { name: "AWS Weekly", domain: "awsweekly.com" },
  { name: "GCP Weekly", domain: "gcpweekly.com" },
  { name: "Azure Weekly", domain: "azureweekly.com" },
  { name: "Kubelist", domain: "kubelist.com" },
  { name: "Kube Weekly", domain: "kubeweekly.io" },

  // Security & Cybersecurity
  { name: "Krebs on Security", domain: "krebsonsecurity.com" },
  { name: "Dark Reading", domain: "darkreading.com" },
  { name: "Security Week", domain: "securityweek.com" },
  { name: "ThreatPost", domain: "threatpost.com" },
  { name: "Cyber Weekly", domain: "cyberweekly.net" },

  // Blockchain & Crypto
  { name: "Decrypt", domain: "decrypt.co" },
  { name: "CoinTelegraph", domain: "cointelegraph.com" },
  { name: "Bankless", domain: "banklesshq.com" },
  { name: "The Defiant", domain: "thedefiant.io" },

  // Tech Industry & General News
  { name: "TechCrunch", domain: "techcrunch.com" },
  { name: "Wired", domain: "wired.com" },
  { name: "The Verge", domain: "theverge.com" },
  { name: "Ars Technica", domain: "arstechnica.com" },
  { name: "The Next Web (TNW)", domain: "thenextweb.com" },
  { name: "Fast Company", domain: "fastcompany.com" },
  { name: "VentureBeat", domain: "venturebeat.com" },
  { name: "Engadget", domain: "engadget.com" },

  // Open Source & Miscellaneous
  { name: "OpenSource.com", domain: "opensource.com" },
  { name: "Red Hat", domain: "redhat.com" },
  { name: "Linux Foundation", domain: "linuxfoundation.org" },
  { name: "DistroWatch", domain: "distrowatch.com" },

  // Developer & Programming Newsletters
  { name: "Dev.to", domain: "dev.to" },
  { name: "Changelog", domain: "changelog.com" },
  { name: "ByteByteGo", domain: "bytebytego.com" },
  { name: "Pointer.io", domain: "pointer.io" },
  { name: "Programming Digest", domain: "programmingdigest.net" },
  { name: "TLDR Tech", domain: "tldr.tech" },
  { name: "Cooperpress", domain: "cooperpress.com" },
  { name: "Bytes", domain: "bytes.dev" },
  { name: "Frontend Horse", domain: "frontend.horse" },
  { name: "UI Dev Newsletter", domain: "ui.dev" },
  
  // System Design & Architecture
  { name: "High Scalability", domain: "highscalability.com" },
  { name: "Architecture Notes", domain: "architecturenotes.co" },
  { name: "System Design Newsletter", domain: "systemdesign.one" },
  
  // Tech Career & Industry
  { name: "Pragmatic Engineer", domain: "pragmaticengineer.com" },
  { name: "Level Up", domain: "levelup.patkua.com" },
  { name: "Software Lead Weekly", domain: "softwareleadweekly.com" },
  { name: "Tech Lead Digest", domain: "techleaddigest.net" },
  
  // AI & ML Specific
  { name: "The Batch", domain: "deeplearning.ai" },
  { name: "The ML Engineer", domain: "themlengineers.com" },
  { name: "The Sequence", domain: "thesequence.ai" },
  { name: "The Algorithm", domain: "thealgorithm.ai" },
  
  // Security
  { name: "Schneier on Security", domain: "schneier.com" },
  { name: "The Hacker News", domain: "thehackernews.com" },
  { name: "Security Newsletter", domain: "securitynewsletter.co" }
];

export const TECH_KEYWORDS = [
  // Programming Languages
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "Ruby",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "TypeScript",
  "PHP",
  "Perl",
  "Scala",
  "Dart",
  "Elixir",
  "Haskell",
  "Lua",
  "R",
  "MATLAB",
  "Shell",
  "Bash",

  // Software Development
  "development",
  "software",
  "app",
  "mobile",
  "web",
  "framework",
  "library",
  "backend",
  "frontend",
  "fullstack",
  "API",
  "SDK",
  "microservices",
  "serverless",
  "REST",
  "GraphQL",
  "gRPC",
  "RPC",
  "CI/CD",
  "testing",
  "unit testing",
  "integration testing",
  "TDD",
  "BDD",
  "functional programming",
  "object-oriented programming",
  "design patterns",
  "scalability",
  "performance optimization",

  // DevOps & Cloud
  "DevOps",
  "Cloud",
  "AWS",
  "Google Cloud",
  "Azure",
  "DigitalOcean",
  "Heroku",
  "Netlify",
  "Vercel",
  "Firebase",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitHub Actions",
  "CI/CD",
  "Kubernetes",
  "Docker",
  "Containers",
  "Serverless",
  "Helm",
  "OpenShift",
  "Cloudflare",
  "Infrastructure as Code",

  // AI & Machine Learning
  "AI",
  "artificial intelligence",
  "machine learning",
  "deep learning",
  "neural networks",
  "NLP",
  "computer vision",
  "GPT",
  "LLM",
  "transformers",
  "data science",
  "big data",
  "analytics",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-Learn",
  "Pandas",
  "NumPy",
  "data engineering",
  "data pipelines",
  "ETL",
  "SQL",
  "NoSQL",
  "Hadoop",
  "Spark",
  "Kafka",
  "Airflow",

  // Security & Cybersecurity
  "cybersecurity",
  "penetration testing",
  "ethical hacking",
  "encryption",
  "hashing",
  "SSL/TLS",
  "authentication",
  "OAuth",
  "JWT",
  "firewalls",
  "SOC",
  "SIEM",
  "zero trust",
  "IAM",
  "data privacy",
  "compliance",
  "ISO 27001",
  "GDPR",
  "SOC2",
  "OWASP",
  "malware",
  "phishing",
  "ransomware",

  // Blockchain & Web3
  "blockchain",
  "Web3",
  "decentralization",
  "Ethereum",
  "Solidity",
  "smart contracts",
  "NFTs",
  "DeFi",
  "Bitcoin",
  "crypto",
  "DApps",
  "Metaverse",
  "ledger",
  "IPFS",
  "gas fees",
  "staking",
  "mining",
  "proof of work",
  "proof of stake",

  // Hardware & Devices
  "hardware",
  "gadgets",
  "devices",
  "laptops",
  "processors",
  "GPUs",
  "chips",
  "components",
  "ARM",
  "x86",
  "Raspberry Pi",
  "Arduino",
  "IoT",
  "5G",
  "edge computing",
  "wearables",
  "robotics",
  "autonomous vehicles",
  "drones",
  "VR",
  "AR",
  "XR",
  "smart home",

  // Tools & Platforms
  "Node.js",
  "React",
  "Vue",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Remix",
  "Electron",
  "Flutter",
  "React Native",
  "SwiftUI",
  "Jetpack Compose",
  "Bootstrap",
  "Tailwind CSS",
  "Material UI",
  "GraphQL",
  "Prisma",
  "Django",
  "Spring Boot",
  "Express.js",
  "NestJS",
  "FastAPI",
  "Flask",
  "Ruby on Rails",
  "Laravel",
  "ASP.NET",
  "Unity",
  "Unreal Engine",
  "WebAssembly",
  "Rust",
  "LLVM",
  "WebRTC",
  "Three.js",

  // Tech Trends & Community
  "technology",
  "innovation",
  "startups",
  "Silicon Valley",
  "tech industry",
  "open source",
  "developer advocacy",
  "tech conferences",
  "hackathons",
  "Google I/O",
  "WWDC",
  "re:Invent",
  "KubeCon",
  "DEFCON",
  "CES",
  "FOSDEM",
  "Black Hat",
  "PyCon",
  "JSConf",

  // Learning & Resources
  "trends",
  "tutorial",
  "guide",
  "course",
  "certification",
  "bootcamp",
  "MOOC",
  "Codecademy",
  "Udemy",
  "Coursera",
  "Pluralsight",
  "edX",
  "LeetCode",
  "HackerRank",
  "Codeforces",
  "competitive programming",
  "tech blogs",
  "GitHub",
  "Stack Overflow",
  "Reddit",
  "Medium",
  "newsletter",
  "update",
  "weekly digest",
];
